CREATE TABLE IF NOT EXISTS AUTH_TOKEN_STATE (
    TOKEN_HASH CHAR(64) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    TOKEN_TYPE VARCHAR(10) NOT NULL,
    EXPIRES_AT DATETIME(3) NOT NULL,
    REVOKED_AT DATETIME(3) NULL,
    CREATED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (TOKEN_HASH),
    INDEX IDX_AUTH_TOKEN_USER_TYPE (USER_ID, TOKEN_TYPE),
    INDEX IDX_AUTH_TOKEN_EXPIRES (EXPIRES_AT),
    CONSTRAINT FK_AUTH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
